// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package namedqueries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}

type Order struct {
	ID          int64
	Userid      pgtype.Int8
	Itemname    pgtype.Text
	Quantity    pgtype.Int8
	Status      pgtype.Text
	Instruction pgtype.Text
}

type User struct {
	ID        int64
	Firstname pgtype.Text
	Lastname  pgtype.Text
	Email     pgtype.Text
	Password  pgtype.Text
	Line1     pgtype.Text
	Line2     pgtype.Text
	City      pgtype.Text
	State     pgtype.Text
	Zipcode   pgtype.Int4
}
