// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package namedqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders(userid,itemName,quantity,status,instruction) VALUES ($1,$2,$3,$4,$5)
`

type CreateOrderParams struct {
	Userid      pgtype.Int8
	Itemname    pgtype.Text
	Quantity    pgtype.Int8
	Status      pgtype.Text
	Instruction pgtype.Text
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder,
		arg.Userid,
		arg.Itemname,
		arg.Quantity,
		arg.Status,
		arg.Instruction,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users(firstname,lastname,email,password,line1,line2,city,state,zipcode) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type CreateUserParams struct {
	Firstname pgtype.Text
	Lastname  pgtype.Text
	Email     pgtype.Text
	Password  pgtype.Text
	Line1     pgtype.Text
	Line2     pgtype.Text
	City      pgtype.Text
	State     pgtype.Text
	Zipcode   pgtype.Int4
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Password,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.Zipcode,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, firstname, lastname, email, password, line1, line2, city, state, zipcode FROM users WHERE email = $1
`

func (q *Queries) GetUser(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.Zipcode,
	)
	return i, err
}
